#!/bin/bash
cd /home/ubuntu/vanvia-api
apt-get -y install software-properties-common
add-apt-repository -y ppa:deadsnakes/ppa
apt-get -y update
apt-get -y install python3.6
apt-get -y install python3-pip
apt-get install -y nginx gunicorn
pip3 install -r requirements.txt
mkdir /home/www && cd /home/www
cp -r ./* /home/www/
/etc/init.d/nginx start
rm /etc/nginx/sites-enabled/default
cp /home/ubuntu/vanvia-api/scripts/vanvia-api /etc/nginx/sites-available/vanvia-api
ln -s /etc/nginx/sites-available/vanvia-api /etc/nginx/sites-enabled/vanvia-api