#!/bin/bash
cd /home/ubuntu/a1jobs-api
apt-get -y install software-properties-common
add-apt-repository -y ppa:deadsnakes/ppa
apt-get -y update
apt-get -y install python3.6
apt-get -y install python3-pip
apt-get install -y nginx gunicorn
pip3 install -r requirements.txt
mkdir /home/www && cd /home/www
cp -r ./* /home/www/
/etc/init.d/nginx start
rm /etc/nginx/sites-enabled/default
cp /home/ubuntu/a1jobs-api/scripts/a1jobs-api /etc/nginx/sites-available/a1jobs-api
ln -s /etc/nginx/sites-available/a1jobs-api /etc/nginx/sites-enabled/a1jobs-api